// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: too_image.proto

package too_image

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Img2ImgMode int32

const (
	Img2ImgMode_ModeDefault    Img2ImgMode = 0 // 普通画图
	Img2ImgMode_ModeControlnet Img2ImgMode = 1 // controlnet模式
)

// Enum value maps for Img2ImgMode.
var (
	Img2ImgMode_name = map[int32]string{
		0: "ModeDefault",
		1: "ModeControlnet",
	}
	Img2ImgMode_value = map[string]int32{
		"ModeDefault":    0,
		"ModeControlnet": 1,
	}
)

func (x Img2ImgMode) Enum() *Img2ImgMode {
	p := new(Img2ImgMode)
	*p = x
	return p
}

func (x Img2ImgMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Img2ImgMode) Descriptor() protoreflect.EnumDescriptor {
	return file_too_image_proto_enumTypes[0].Descriptor()
}

func (Img2ImgMode) Type() protoreflect.EnumType {
	return &file_too_image_proto_enumTypes[0]
}

func (x Img2ImgMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Img2ImgMode.Descriptor instead.
func (Img2ImgMode) EnumDescriptor() ([]byte, []int) {
	return file_too_image_proto_rawDescGZIP(), []int{0}
}

type Img2ImgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode                  Img2ImgMode `protobuf:"varint,1,opt,name=mode,proto3,enum=tooimage.Img2ImgMode" json:"mode,omitempty"`
	InitImages            string      `protobuf:"bytes,2,opt,name=init_images,json=initImages,proto3" json:"init_images,omitempty"` // 初始图片
	Prompt                string      `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	DenoisingStrength     float64     `protobuf:"fixed64,4,opt,name=denoising_strength,json=denoisingStrength,proto3" json:"denoising_strength,omitempty"`
	Width                 int32       `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height                int32       `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	ControlnetInputImages string      `protobuf:"bytes,7,opt,name=controlnet_input_images,json=controlnetInputImages,proto3" json:"controlnet_input_images,omitempty"`
}

func (x *Img2ImgReq) Reset() {
	*x = Img2ImgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_too_image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Img2ImgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Img2ImgReq) ProtoMessage() {}

func (x *Img2ImgReq) ProtoReflect() protoreflect.Message {
	mi := &file_too_image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Img2ImgReq.ProtoReflect.Descriptor instead.
func (*Img2ImgReq) Descriptor() ([]byte, []int) {
	return file_too_image_proto_rawDescGZIP(), []int{0}
}

func (x *Img2ImgReq) GetMode() Img2ImgMode {
	if x != nil {
		return x.Mode
	}
	return Img2ImgMode_ModeDefault
}

func (x *Img2ImgReq) GetInitImages() string {
	if x != nil {
		return x.InitImages
	}
	return ""
}

func (x *Img2ImgReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Img2ImgReq) GetDenoisingStrength() float64 {
	if x != nil {
		return x.DenoisingStrength
	}
	return 0
}

func (x *Img2ImgReq) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Img2ImgReq) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Img2ImgReq) GetControlnetInputImages() string {
	if x != nil {
		return x.ControlnetInputImages
	}
	return ""
}

type Img2ImgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutImages []string `protobuf:"bytes,1,rep,name=out_images,json=outImages,proto3" json:"out_images,omitempty"` // 输出图片
}

func (x *Img2ImgRsp) Reset() {
	*x = Img2ImgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_too_image_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Img2ImgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Img2ImgRsp) ProtoMessage() {}

func (x *Img2ImgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_too_image_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Img2ImgRsp.ProtoReflect.Descriptor instead.
func (*Img2ImgRsp) Descriptor() ([]byte, []int) {
	return file_too_image_proto_rawDescGZIP(), []int{1}
}

func (x *Img2ImgRsp) GetOutImages() []string {
	if x != nil {
		return x.OutImages
	}
	return nil
}

var File_too_image_proto protoreflect.FileDescriptor

var file_too_image_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x6f, 0x6f, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x74, 0x6f, 0x6f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x02, 0x0a, 0x0a, 0x49, 0x6d,
	0x67, 0x32, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x74, 0x6f, 0x6f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2e, 0x49, 0x6d, 0x67, 0x32, 0x49, 0x6d, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x2d, 0x0a, 0x12,
	0x64, 0x65, 0x6e, 0x6f, 0x69, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x64, 0x65, 0x6e, 0x6f, 0x69, 0x73,
	0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6e, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6e, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x22, 0x2b, 0x0a, 0x0a, 0x49, 0x6d, 0x67, 0x32, 0x49, 0x6d, 0x67, 0x52, 0x73, 0x70, 0x12,
	0x1d, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x32,
	0x0a, 0x0b, 0x49, 0x6d, 0x67, 0x32, 0x49, 0x6d, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x4d, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6e, 0x65, 0x74,
	0x10, 0x01, 0x32, 0x64, 0x0a, 0x0c, 0x54, 0x6f, 0x6f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x74,
	0x74, 0x70, 0x12, 0x54, 0x0a, 0x07, 0x49, 0x6d, 0x67, 0x32, 0x49, 0x6d, 0x67, 0x12, 0x14, 0x2e,
	0x74, 0x6f, 0x6f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x67, 0x32, 0x49, 0x6d, 0x67,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x6f, 0x6f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x49,
	0x6d, 0x67, 0x32, 0x49, 0x6d, 0x67, 0x52, 0x73, 0x70, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x17, 0x22, 0x12, 0x2f, 0x74, 0x6f, 0x6f, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2f, 0x69, 0x6d,
	0x67, 0x32, 0x69, 0x6d, 0x67, 0x3a, 0x01, 0x2a, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x61, 0x74, 0x73, 0x75, 0x6b, 0x69, 0x73,
	0x75, 0x6e, 0x32, 0x30, 0x32, 0x30, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f,
	0x6a, 0x2f, 0x74, 0x6f, 0x6f, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_too_image_proto_rawDescOnce sync.Once
	file_too_image_proto_rawDescData = file_too_image_proto_rawDesc
)

func file_too_image_proto_rawDescGZIP() []byte {
	file_too_image_proto_rawDescOnce.Do(func() {
		file_too_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_too_image_proto_rawDescData)
	})
	return file_too_image_proto_rawDescData
}

var file_too_image_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_too_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_too_image_proto_goTypes = []interface{}{
	(Img2ImgMode)(0),   // 0: tooimage.Img2ImgMode
	(*Img2ImgReq)(nil), // 1: tooimage.Img2ImgReq
	(*Img2ImgRsp)(nil), // 2: tooimage.Img2ImgRsp
}
var file_too_image_proto_depIdxs = []int32{
	0, // 0: tooimage.Img2ImgReq.mode:type_name -> tooimage.Img2ImgMode
	1, // 1: tooimage.TooImageHttp.Img2Img:input_type -> tooimage.Img2ImgReq
	2, // 2: tooimage.TooImageHttp.Img2Img:output_type -> tooimage.Img2ImgRsp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_too_image_proto_init() }
func file_too_image_proto_init() {
	if File_too_image_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_too_image_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Img2ImgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_too_image_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Img2ImgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_too_image_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_too_image_proto_goTypes,
		DependencyIndexes: file_too_image_proto_depIdxs,
		EnumInfos:         file_too_image_proto_enumTypes,
		MessageInfos:      file_too_image_proto_msgTypes,
	}.Build()
	File_too_image_proto = out.File
	file_too_image_proto_rawDesc = nil
	file_too_image_proto_goTypes = nil
	file_too_image_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TooImageHttpClient is the client API for TooImageHttp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TooImageHttpClient interface {
	Img2Img(ctx context.Context, in *Img2ImgReq, opts ...grpc.CallOption) (*Img2ImgRsp, error)
}

type tooImageHttpClient struct {
	cc grpc.ClientConnInterface
}

func NewTooImageHttpClient(cc grpc.ClientConnInterface) TooImageHttpClient {
	return &tooImageHttpClient{cc}
}

func (c *tooImageHttpClient) Img2Img(ctx context.Context, in *Img2ImgReq, opts ...grpc.CallOption) (*Img2ImgRsp, error) {
	out := new(Img2ImgRsp)
	err := c.cc.Invoke(ctx, "/tooimage.TooImageHttp/Img2Img", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TooImageHttpServer is the server API for TooImageHttp service.
type TooImageHttpServer interface {
	Img2Img(context.Context, *Img2ImgReq) (*Img2ImgRsp, error)
}

// UnimplementedTooImageHttpServer can be embedded to have forward compatible implementations.
type UnimplementedTooImageHttpServer struct {
}

func (*UnimplementedTooImageHttpServer) Img2Img(context.Context, *Img2ImgReq) (*Img2ImgRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Img2Img not implemented")
}

func RegisterTooImageHttpServer(s *grpc.Server, srv TooImageHttpServer) {
	s.RegisterService(&_TooImageHttp_serviceDesc, srv)
}

func _TooImageHttp_Img2Img_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Img2ImgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TooImageHttpServer).Img2Img(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tooimage.TooImageHttp/Img2Img",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TooImageHttpServer).Img2Img(ctx, req.(*Img2ImgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TooImageHttp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tooimage.TooImageHttp",
	HandlerType: (*TooImageHttpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Img2Img",
			Handler:    _TooImageHttp_Img2Img_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "too_image.proto",
}
